<?php

/**
 * Implementation of hook_node_info
 *
 * @return unknown
 */
function ebook_node_info() {
	$info = array();
	$info['ebook'] = array(
		'name' => t('EBook'),
		'base' => 'node_content',
	);
	return $info;
}

/**
 * Implementation of hook_menu()
 */
function ebook_menu() {
  $items['allEBookPage'] = array(
    'title' => t('All EBooks'),
    'page callback' => 'all_ebook_callback',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'main-menu',
    'weight' => 4,
  );
  $items['myEBookPage'] = array(
    'title' => t('My EBooks'),
    'page callback' => 'my_ebook_callback',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'main-menu',
    'weight' => 4,
  );
  return $items;
}


/**
 * Page callback: displaying a page with php template
 *
 * @see ebook_menu()
 */
function all_ebook_callback(){
  global $user;
  $build = array();

  $query = db_select('node', 'n')->extend('PagerDefault');
  $nids = $query
    ->fields('n', array('nid', 'title'))
    ->condition('type', 'ebook')
    ->condition('status', 1)
    ->orderBy('nid', 'DESC')
    ->execute()
    ->fetchCol();

  if (!empty($nids)) {
    $nodes = node_load_multiple($nids);
    $build += node_view_multiple($nodes);
    $build['pager'] = array(
      '#theme' => 'pager',
      '#weight' => 5,
    );
  }
  else {
    drupal_set_message(t('No ebook has been created.'));
  }

  return $build;
}


/**
 * Page callback: displaying a page with php template
 *
 * @see ebook_menu()
 */
function my_ebook_callback(){
  global $user;
  $uid = $user->uid;
  $build = array();

  $query = db_select('node', 'n')->extend('PagerDefault');
  $nids = $query
    ->fields('n', array('nid', 'title'))
    ->condition('type', 'ebook')
    ->condition('status', 1)
    ->condition('uid', $uid, '=')
    ->orderBy('nid', 'DESC')
    ->execute()
    ->fetchCol();

  if (!empty($nids)) {
    $nodes = node_load_multiple($nids);
    $build += node_view_multiple($nodes);
    $build['pager'] = array(
      '#theme' => 'pager',
      '#weight' => 5,
    );
  }
  else {
    drupal_set_message(t('No ebook has been created by you.'));
  }

  return $build;
}

